
# WIIIP

# this is a default.conf, we need to provide other conf files to test server features (CGI/upload etc)

server {
    # 80 is standard HTTP port but on linux we need root rights to bind a port < 1024
    # we use 8080 to bypass that in the dev world
    # 127.0.0.1 to listen only locally, if we want to listen on all interfaces : 0.0.0.0
    listen 127.0.0.1:8080;

    # the default value for client_max_body_size directive in nginx is 1 MB
    client_max_body_size 1M;

    # common error a serveur can encounter
    error_page 400 /errors/400.html;
    error_page 403 /errors/403.html;
    error_page 404 /errors/404.html;
    error_page 405 /errors/405.html;
    error_page 413 /errors/413.html;
    error_page 500 /errors/500.html;
    error_page 501 /errors/501.html;
    error_page 505 /errors/505.html;

    # root directory served by this server block
    root www/html/;

    # TODO location {}

}

server {

}