# ./webserv conf/demo_upload.conf and open http://127.0.0.1:8084
# curl -X POST http://127.0.0.1:8084/upload/filename.txt --data-binary "hello" => upload a file
# curl -L http://127.0.0.1:8084/received => (-L follows the trailing slash redirect, browse uploaded files)

server {

    listen 127.0.0.1:8084;

    client_max_body_size 10M;

    error_page 400 www/errors/400.html;
    error_page 403 www/errors/403.html;
    error_page 404 www/errors/404.html;
    error_page 405 www/errors/405.html;
    error_page 413 www/errors/413.html;
    error_page 500 www/errors/500.html;
    error_page 501 www/errors/501.html;
    error_page 505 www/errors/505.html;

    # info page
    location / {
        methods GET;
        root www/demo/upload/html;
        index index.html;
        autoindex off;
    }

    location /upload {
        methods POST;
        upload_path www/demo/upload/received;
        autoindex off;
    }

    # browse uploaded files
    location /received {
        methods GET;
        root www/demo/upload;
        autoindex on;
    }

    location /css {
        methods GET;
        root www;
        autoindex off;
    }
}
