# ./webserv conf/demo_redirect.conf and open http://127.0.0.1:8083/redirect
# curl -v http://127.0.0.1:8083/redirect => (-v shows the 301 and Location header)
# curl -L http://127.0.0.1:8083/redirect => (-L follows the redirect, shows the final page)

server {

    listen 127.0.0.1:8083;

    client_max_body_size 10M;

    error_page 400 www/errors/400.html;
    error_page 403 www/errors/403.html;
    error_page 404 www/errors/404.html;
    error_page 405 www/errors/405.html;
    error_page 413 www/errors/413.html;
    error_page 500 www/errors/500.html;
    error_page 501 www/errors/501.html;
    error_page 505 www/errors/505.html;

    # redirection - no root, no methods needed, just a code and a destination
    location /redirect {
        return 301 /; # 301 = moved permanently, redirects to /
    }

    location / {
        methods GET;
        root www/demo/redirect;
        index index.html;
        autoindex off;
    }

    location /css {
        methods GET;
        root www;
        autoindex off;
    }
}