#!/bin/bash
# CGI script - reads HTTP_COOKIE environment variable and displays it as HTML
# purpose: demonstrate that the server correctly passes client cookies to CGI
# scripts via the HTTP_COOKIE environment variable (standard CGI spec).
# this script does NOT modify any cookie or session data - it only reads and
# displays what the browser already sent. visit_count shown here was set by
# the /cookie-session page, not by this script.

echo "Content-Type: text/html"
echo ""
echo "<!DOCTYPE html>"
echo "<html><head><title>cookie info - CGI</title></head><body>"
echo "<h2>Cookie info (via bash CGI)</h2>"
echo "<p>This page was generated by a <strong>bash</strong> CGI script (<code>cookie_info.sh</code>).</p>"
echo "<hr>"

echo "<h3>How this demo works</h3>"
echo "<ol>"
echo "<li>Visit <a href='/cookie-session/'>/cookie-session/</a> - the C++ server creates a session and sets two cookies in the HTTP response: <code>session_id</code> and <code>visit_count</code>. The visit counter increments on each page load.</li>"
echo "<li>Visit this page - the browser automatically sends those cookies back in the request <code>Cookie:</code> header. The server forwards that header to this CGI script as the environment variable <code>HTTP_COOKIE</code>.</li>"
echo "<li>The <code>visit_count</code> you see below is the value that was stored by the C++ server and carried here by the browser cookie. This script never modified it - it just reads what the browser sent.</li>"
echo "</ol>"
echo "<p>This demonstrates the full cookie pipeline: <strong>server sets cookie -&gt; browser stores and sends it back -&gt; CGI script reads it via HTTP_COOKIE</strong>.</p>"
echo "<hr>"

if [ -z "$HTTP_COOKIE" ]; then
    echo "<p>No cookies found - visit <a href='/cookie-session/'>/cookie-session/</a> first, then come back here.</p>"
else
    echo "<p><strong>HTTP_COOKIE received by this script:</strong></p>"
    echo "<p><code>$HTTP_COOKIE</code></p>"
fi

echo "<hr>"
echo "<p><a href='/cookie-session/'>Back to cookie session demo</a></p>"
echo "</body></html>"
