#!/bin/bash
# CGI script — reads HTTP_COOKIE environment variable and displays it as HTML
# demonstrates: second CGI type (bash), cookies passed to CGI via env vars

echo "Content-Type: text/html"
echo ""
echo "<!DOCTYPE html>"
echo "<html><head><title>cookie info - CGI</title></head><body>"
echo "<h2>Cookie info (via CGI)</h2>"
echo "<p>This page was generated by a bash CGI script.</p>"
echo "<p>The server passes cookies to CGI via the <code>HTTP_COOKIE</code> environment variable.</p>"
echo "<hr>"

if [ -z "$HTTP_COOKIE" ]; then
    echo "<p>No cookies found in this request.</p>"
else
    echo "<p><strong>HTTP_COOKIE:</strong> <code>$HTTP_COOKIE</code></p>"
fi

echo "<hr>"
echo "<p><a href='/session'>Back to session demo</a></p>"
echo "</body></html>"
