#!/bin/bash
# CGI script - reads HTTP_COOKIE environment variable and displays it as HTML
# purpose: demonstrate that the server correctly passes client cookies to CGI
# scripts via the HTTP_COOKIE environment variable (standard CGI spec).
# this script does NOT modify any cookie or session data - it only reads and
# displays what the browser already sent. visit_count shown here was set by
# the /cookie-session page, not by this script.

echo "Content-Type: text/html"
echo ""
echo "<!DOCTYPE html>"
echo "<html>"
echo "<head>"
echo "  <title>cookie info - CGI</title>"
echo "  <link rel='stylesheet' href='/css/css-pokemon-gameboy.css'>"
echo "  <link rel='stylesheet' href='/css/webserv.css'>"
echo "</head>"
echo "<body>"
echo "<div class='framed primary'>"
echo "<h2>webserv - cookie info (bash CGI)</h2>"
echo "<p class='message'>This page was generated by a <strong>bash</strong> CGI script (<code>cookie_info.sh</code>).</p>"
echo "<hr>"

echo "<h3>How this demo works</h3>"
echo "<ol>"
echo "<li class='message'>Visit <a href='/cookie-session/'>/cookie-session/</a> - the C++ server creates a session and sets two cookies: <code>session_id</code> and <code>visit_count</code>. The counter increments on each page load.</li>"
echo "<li class='message'>Visit this page - the browser sends those cookies back via the <code>Cookie:</code> header. The server forwards it to this script as <code>HTTP_COOKIE</code>.</li>"
echo "<li class='message'>The <code>visit_count</code> below was stored by the C++ server and carried here by the browser. This script never modified it - it just reads what the browser sent.</li>"
echo "</ol>"
echo "<p class='message'>Full pipeline: <strong>server sets cookie -&gt; browser stores and sends it back -&gt; CGI reads it via HTTP_COOKIE</strong>.</p>"
echo "<hr>"

if [ -z "$HTTP_COOKIE" ]; then
    echo "<p class='message'>No cookies found - visit <a href='/cookie-session/' class='button'>/cookie-session/</a> first, then come back here.</p>"
else
    echo "<p class='message'><span>HTTP_COOKIE:</span></p>"
    echo "<p><code>$HTTP_COOKIE</code></p>"
fi

echo "<hr>"
echo "<a href='/cookie-session/' class='button'>Back to cookie session demo</a>"
echo "</div>"
echo "</body></html>"
